import type { Metadata } from "next"
import { Libre_Franklin } from "next/font/google"
import "./globals.css"
import Providers from "./Providers"

const libre_franklin = Libre_Franklin({ subsets: ["latin"] })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <Providers>
      <html lang="en">
        <body className={`${libre_franklin.className} text-content-base`}>{children}</body>
      </html>
    </Providers>
  )
}
